"""Initial

Revision ID: 938e1abc0db6
Revises: 
Create Date: 2026-01-23 11:33:51.516961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e1abc0db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('nome_administradora', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administradoras')),
    sa.UniqueConstraint('nome_administradora', name=op.f('uq_administradoras_nome_administradora'))
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_aniversario_contrato', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ultimo_parabens_enviado', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes')),
    sa.UniqueConstraint('cpf', name=op.f('uq_clientes_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_clientes_email'))
    )
    op.create_table('clientes_confiauto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes_confiauto')),
    sa.UniqueConstraint('cpf', name=op.f('uq_clientes_confiauto_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_clientes_confiauto_email'))
    )
    op.create_table('operadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_operadora', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operadoras')),
    sa.UniqueConstraint('nome_operadora', name=op.f('uq_operadoras_nome_operadora'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('username', name=op.f('uq_usuarios_username'))
    )
    op.create_table('confiauto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_confiauto_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_marca', sa.String(length=50), nullable=True),
    sa.Column('veiculo_modelo', sa.String(length=50), nullable=True),
    sa.Column('veiculo_ano', sa.Integer(), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=True),
    sa.Column('veiculo_chassi', sa.String(length=50), nullable=True),
    sa.Column('valor_veiculo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_protecao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_ativacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_contratacao', sa.Date(), nullable=True),
    sa.Column('data_vigencia', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_confiauto_id'], ['clientes_confiauto.id'], name=op.f('fk_confiauto_cliente_confiauto_id_clientes_confiauto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confiauto'))
    )
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cobertura', sa.Text(), nullable=True),
    sa.Column('tipo_plano', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('operadora_id', sa.Integer(), nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=True),
    sa.Column('acomodacao', sa.String(length=50), nullable=True),
    sa.Column('administradora', sa.String(length=100), nullable=True),
    sa.Column('entidade', sa.String(length=100), nullable=True),
    sa.Column('beneficios', sa.Text(), nullable=True),
    sa.Column('data_vigencia', sa.Date(), nullable=True),
    sa.Column('created_by_username', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['operadora_id'], ['operadoras.id'], name=op.f('fk_planos_operadora_id_operadoras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planos')),
    sa.UniqueConstraint('nome_plano', name=op.f('uq_planos_nome_plano'))
    )
    op.create_table('precos_faixa_etaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('idade_min', sa.Integer(), nullable=False),
    sa.Column('idade_max', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], name=op.f('fk_precos_faixa_etaria_plano_id_planos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_precos_faixa_etaria'))
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('data_vigencia', sa.Date(), nullable=True),
    sa.Column('origem', sa.Text(), nullable=True),
    sa.Column('natureza', sa.Text(), nullable=True),
    sa.Column('promocao', sa.Text(), nullable=True),
    sa.Column('numeros_vida', sa.Integer(), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('premiacao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('premiacao_paga', sa.Boolean(), nullable=True),
    sa.Column('comissao_paga', sa.Boolean(), nullable=True),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tipo_plano', sa.String(length=120), nullable=True),
    sa.Column('administradora', sa.String(length=120), nullable=True),
    sa.Column('titular_nome', sa.String(length=120), nullable=True),
    sa.Column('titular_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_vendas_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], name=op.f('fk_vendas_plano_id_planos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    op.drop_table('precos_faixa_etaria')
    op.drop_table('planos')
    op.drop_table('confiauto')
    op.drop_table('usuarios')
    op.drop_table('operadoras')
    op.drop_table('clientes_confiauto')
    op.drop_table('clientes')
    op.drop_table('administradoras')
    # ### end Alembic commands ###
